### ISSUE TITLE
Település > autocomplete, hierarchia

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#1]
- [ ] 3 beírt karakter után egészítse ki (pl. mint a [sajtóadatbázis keresője](https://adatbazis.k-monitor.hu/))
- [ ] ha van kiválasztva megye, csak azok közül lehessen választani (nem prioritás)

**Comment by law909** [comment]
@pisipite ha több megye van kiválasztva, akkor bármelyikbe tartozó települések közül lehessen választani?

**Comment by law909** [comment]
#2 ütközik. Település és irszám szűrőnek párhuzamosan ugyanazt kell tartalmaznia. Csak az egyiket kellene figyelembe venni, egyelőre nem tudom mitől függően.

**Comment by pisipite** [comment]
> sen vá

igen!

**Comment by pisipite** [comment]
> #2 ütközik. Település és irszám szűrőnek párhuzamosan ugyanazt kell tartalmaznia. Csak az egyiket kellene figyelembe venni, egyelőre nem tudom mitől függően.

az nem megoldható, hogy csak az egyiket tudja megadni a felhasználó?
