### ISSUE TITLE
találatok közt nem jelenik meg név

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#120]
egyes cégcsoporttal felcímkézett találati sorokban nem jelenik meg név. pl.: 
![image](https://user-images.githubusercontent.com/25430950/203521710-68b6ddba-c6b2-4004-9c51-839dd56c5187.png)

**Comment by Cooty** [comment]
@pisipite Megszereltem, kint van élesen. Kérlek teszteld te is!

**Comment by pisipite** [comment]
jónak tűnik! köszi szépen!
