### ISSUE TITLE
Export gomb

### ISSUE THREAD

**Issue by law909** [Code-for-Hungary/agrartamfront#17]
Csak bedobtam, a helyére kellene rakni.

**Comment by Cooty** [comment]
@law909  - Itt lenne pár kérdésem.

- Hol van ennek a gombnak a "helye"? Az eredeti dizájnon nem szerepel.
- Mit csinál ez a gomb? Jelenleg ha rákattintok (a localhoston futó verziómban) nem történik semmi. A végfelhasználó szempontjából mi a funkciója és a user-journeyben hol van a szerepe?

Én úgy képzelem el a működést, hogy alapból csak a "Keresés" és a "Részletes keresés" látszanak, majd (opcionálisan megadok keresési feltételeket) rákattintok a "Keresés"-re aztán megjelenik egy találati lista, és aztán látom ezt a gombot a találati lista alján, amivel kiexportálhatom (azaz letölthetem) a listát Excelben, PDF-ben, CSV-ben vagy mit tudom én miben? Javíts ki, ha nem így működik.

**Comment by law909** [comment]
Pont így kéne működjön, csak eredetileg más funkciója van: Attila kiexportál egy adatkupacot, módosít rajta, hozzáad sorokat és visszatölti. A visszatöltő el van dugva.
Azért került oda ahol van, hogy ne kelljen egy privát szűrőfelület.
Ettől függetlenül lehet úgy ahogy mondod, kérdezzük meg @pisipite -t.

**Comment by pisipite** [comment]
aha, az tűnik a legjobbnak user journey szempontból, amit Kuti írsz. 
viszont 1) amíg nincs keresési eredmények táblánk és/vagy 2) arra jutunk, hogy (pl.) 100.000 fölötti találatot ne is próbáljunk megjeleníteni webes módon, akkor már a keresési találatok megjelenítése előtt hasznos lenne egy export gomb.

az tök szuper, ha csak az adminba bejelentkezve itt látszik az import funkció.

**Comment by Cooty** [comment]
lsd #62

**Comment by pisipite** [comment]
kúl!
