### ISSUE TITLE
z-index gondok

### ISSUE THREAD

**Issue by law909** [Code-for-Hungary/agrartamfront#18]
Az Alap+Forrás+Cégcsoport, a Támogatott entitás és a Támogatás összeg két gombjának z-indexe üti egymást.

**Comment by Cooty** [comment]
@law909 - Tudsz kérlek screenshotokat vagy videót csatolni arról, hogy ez pontosan hogyan is néz ki? Megpróbáltam reprodukálni, de nálam semmi nem lóg rá semmire (lsd csatolt screenshotokat).

Tesztelt platformok:
- Chrome 104.0.5112.101 / Linux
- Firefox 103.0 / Linux 

![image](https://user-images.githubusercontent.com/6146591/186370097-cd2f02cc-5dde-45ce-b004-9bd9a3227044.png)
![image](https://user-images.githubusercontent.com/6146591/186370155-b42d3e8b-d426-4ee4-9e00-8f960099eca6.png)
![image](https://user-images.githubusercontent.com/6146591/186370227-f17572a8-3479-40d0-995c-63d3cad784d8.png)

**Comment by pisipite** [comment]
jogcím is ilyet ad:
![image](https://user-images.githubusercontent.com/25430950/186387731-d8a711a4-ff18-4a7c-a03b-696605f64d87.png)
[Verzió: 1.42.97 Chromium: 104.0.5112.102 (Hivatalos verzió) (64 bites)](https://brave.com/latest/)

**Comment by Cooty** [comment]
Fixed #22
