### ISSUE TITLE
keresés hibaüzenet

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#19]
keresés helyett hibaüzenetet ad: 
![image](https://user-images.githubusercontent.com/25430950/186388114-38bbdb9a-5d0e-47f8-b6c7-b8ad4bd7773e.png)

**Comment by pisipite** [comment]
> @pisipite Legközelebb ilyen esetben a kérdéses keresést is mellékeld.

minden keresésre ezt az üzenetet adta :)

**Comment by pisipite** [comment]
export gombra nyomásnál is ezt adja.

**Comment by law909** [comment]
Nekem tökéletesen működik és nincs hiba log sem. Cache-elés problémára gyanakszom. @pisipite nyomj shift+f5-öt, utána próbáld ki.
