### ISSUE TITLE
Név > autocomplete, multiselect

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#3]
(nem prioritás) (3 beírt karakter után) egészítse ki a meglévő halmazból (pl. mint a [sajtóadatbázis keresője](https://adatbazis.k-monitor.hu/)). emellett még az is jó lenne, ha lehetne egyszerre többet kiválasztani.
Bálint korábban írta, hogy _eszement sok adatunk van, csinalok egy tesztet_. én sem vagyok biztos benne, hogy ez így együtt jól működne.

**Comment by law909** [comment]
@pisipite A név szűrő kifejezetten szabadon beírós. A következő operátorok használhatók a következő módokon:
mészáros lőrinc
Minden sor amiben a két szó valamelyike szerepel

+mészáros +lőrinc
Minden sor amiben mindkét szó szerepel 

+mészáros lőrinc
Minden sor amiben szerepel a "mészáros", de előrébb kerülnek azok amikben a "lőrinc" is szerepel

+mészáros -lőrinc
Minden sor amiben szerepel a "mészáros" de a "lőrinc" nem

+mészáros ~lőrinc
Minden sor amiben szerepel a "mészáros", de hátrébb kerülnek azok amikben a "lőrinc" is szerepel

mészáros*
Minden sor amiben szerepel "mészáros" kezdetű szó

"mészáros lőrinc"
Minden sor amiben a pontos "mészáros lőrinc" kifejezés szerepel

Annyit tervezek módosítani, hogy ha az első eset áll fenn (mészáros lőrinc), akkor idézőjelek közé teszem, vagy minden szó elé teszek egy "+" jelet.

Mit gondolsz erről? Hogyan tegyük felhasználóbaráttá?

**Comment by pisipite** [comment]
abból indulnék ki, hogy a felhasználó amit tud, azt beírja. szóval a legtöbb esetben +mészáros +lőrinc a nyerő, ezt venném alapnak, a többit hátrébb sorolnám. nem tudom, mennyien ismerik ezeknek a jeleknek az alkalmazását, de jó, ha működik így is.

**Comment by law909** [comment]
Ha van a keresésben vezérlő karakter, akkor felteszem hogy a user tudja mit akar, nem nyúlok a kereséséhez.
Ha nincs vezérlő karakter, akkor felteszem hogy minden szóra keres, tehát minden szó elé teszek egy "+"-t.

**Comment by pisipite** [comment]
> Ha van a keresésben vezérlő karakter, akkor felteszem hogy a user tudja mit akar, nem nyúlok a kereséséhez. Ha nincs vezérlő karakter, akkor felteszem hogy minden szóra keres, tehát minden szó elé teszek egy "+"-t.

igen, kb. így értettem én is. kösz!

**Comment by pisipite** [comment]
az miért lehet, hogy ha csak tiborcz-ot írok be név keresésre 2021-es évet megadva, akkor nálunk jóval kevesebb találatot ad, mint az [mvh oldalán](https://www.mvh.allamkincstar.gov.hu/tamogatasi-adatok)?
![image](https://user-images.githubusercontent.com/25430950/189664518-5b7cf612-daac-496d-9547-f69fb8942c51.png)

![image](https://user-images.githubusercontent.com/25430950/189664445-3adaa182-f5fb-4472-9dac-093d5e35b5f2.png)

**Comment by pisipite** [comment]
azon még jó lenne finomítani, hogy cégnevek esetében az adatbázisban nem szereplőre ne adja ki az összes azonos cégtípust. pl. _Taby-Agro Kft_ berírása esetén a _Taby-Agro_-ra nem talál, ezért gondolom kilistáz egy csomó _Kft_-t.

**Comment by law909** [comment]
> azon még jó lenne finomítani, hogy cégnevek esetében az adatbázisban nem szereplőre ne adja ki az összes azonos cégtípust. pl. _Taby-Agro Kft_ berírása esetén a _Taby-Agro_-ra nem talál, ezért gondolom kilistáz egy csomó _Kft_-t.

`Taby-Agro Kft`-ből `+Taby-Agro +Kft` lesz, ami elvileg olyan találatokat ad, amikben mindkét szó szerepel. Látom, hogy a gyakorlatban sajnos nem így van, valószínűleg mivel `Taby-Agro`-t nem talál, valamit azért adna vissza, így jönnek a `Kft`-k.
Kikerülhető ha idézőjelek közé teszed a kereső kifejezést: `"Taby-Agro Kft`

**Comment by law909** [comment]
> az miért lehet, hogy ha csak tiborcz-ot írok be név keresésre 2021-es évet megadva, akkor nálunk jóval kevesebb találatot ad, mint az [mvh oldalán](https://www.mvh.allamkincstar.gov.hu/tamogatasi-adatok)? 

Mindkettő 34 sort ad eredményül.

**Comment by law909** [comment]
Folytassuk itt: https://github.com/Code-for-Hungary/agrartamapi/issues/14
