### ISSUE TITLE
Támogatás összege > csúszka

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#4]
tól-ig meghatározás (leginkább vizuálisan), valami ilyesmire gondoltam ([ecipo.hu keresője](https://www.ecipo.hu/ferfi.html)):
![image](https://user-images.githubusercontent.com/25430950/183870356-0d84a886-82b1-42cc-b55a-4b927dd38528.png)

**Comment by law909** [comment]
@pisipite dizájn nélkül kész van. Kénytelen voltam 1000-rel osztani az értékeket, de szerintem még ez is kevés lesz.

**Comment by pisipite** [comment]
tök jó így!

**Comment by pisipite** [comment]
ne számmal (_1000 Ft_), hanem betűvel legyen a felszorzás (_ezer Ft_) kiírva.
