### ISSUE TITLE
Jogi személy/Természetes személy/Gender szűrő logika

### ISSUE THREAD

**Issue by law909** [Code-for-Hungary/agrartamfront#5]
Multiselect az igény, de mire szűrjek, ha pl. jogi személy és természetes személy és férfi ki van választva?

**Comment by pisipite** [comment]
szerintem elengedhetjük azt, hogy ha mindkettő ki van választva, akkor lehessen nemet is választani. egyszerűen adja ki az összes természetes személy. ha pedig csak természetest jelöli ki, akkor jelenjen meg a nemválasztó (ahogy most is van).
