### ISSUE TITLE
irányítószám és település szűrő működése

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#51]
irányítószám csak pozitív szám lehessen.

**Comment by law909** [comment]
Sajnos nem egyszerű ez a probléma. Azt gondoljuk idealisták, hogy az országban minden településnek/településrésznek saját egyedi irányítószáma van és minden országos nyilvántartás ezzel azonosítja őket. Sajnos ez nem így van. 
- a postai település jegyzékben ir.szám és település név van, megye nincs. Egy irszám adott esetben több településhez is tartozik
- az állami nyilvántartásban (forrás: valasztas.hu) pl. a választások során nem is használja az ir.számot mint azonosítót, helyette minden településnek van saját egyedi (3 karakteres amiben előnullázott sorszám van, haha) azonosítója, itt a települések a megyéjükhöz is hozzá vannak kapcsolva. A postai nyilvántartásban azonos ir.számot kapott települések itt saját egyedi azonosítóval rendelkeznek.
- az agrár adatbázisban a települések (akárcsak az összes többi adat) látszólag kézzel vannak rögzítve, úgy ahogy beérkezhettek. Pl. van Tedej, Hajdúnánás-Tedej, Tedej és utcába beírt Hajdúnánás, ami mind ugyanaz a településrész.

Mivel ebben a három adatbázisban a név a közös pont, a hibátlan konszolidációra nem látok lehetőséget.

Az agrár adatbázisból fel lehet építeni egy irszám, település listát, azt használhatjuk lenyílóban. @pisipite azt döntsétek el, hogy szabad szavas, egyet kiválasztós vagy többet kiválasztós irszám/település szűrőt akartok:
- szabad szavas: a látogató azt ír be amit akar (pl. 'pest', ami találatot adhat Budapestre, Pestszentlőrincre stb), max. segítünk a lehetőségek listájával
- egyet kiválasztós: az ir.számot és a települést egyesítjük, a létezők listájából lehet egyet választani, akár megyére szűrten
- többet kiválasztós: mint az előző, csak többet ki lehet választani

**Comment by law909** [comment]
#1 #2 kapcsolódik

**Comment by law909** [comment]
@pisipite írta `(3 beírt karakter után) egészítse ki a meglévő halmazból (pl. mint a [sajtóadatbázis keresője](https://adatbazis.k-monitor.hu/))`

**Comment by law909** [comment]
@pisipite írta (Település szűrő)
- [ ] 3 beírt karakter után egészítse ki (pl. mint a [sajtóadatbázis keresője](https://adatbazis.k-monitor.hu/))
- [ ] ha van kiválasztva megye, csak azok közül lehessen választani (nem prioritás)

Ha több megye van kiválasztva, akkor azok településeiből lehessen választani.

**Comment by pisipite** [comment]
a mostani változat tök szép!

**Comment by Cooty** [comment]
Megadtam az input type="number"-nek egy min="0" attribútumot. Ez Biztosítja, hogy amikor kis nyilacskákkal (vagy az egérgörgővel, vagy a fel/le nyilakkal) lépkedsz az input mezőben, akkor ne mehessen 0 alá. Illetve ha bekopipésztelsz egy negatív számot vágólapról, akkor kiír egy figyelmeztető üzit (nálam angolul, de ez elvileg igazodik a böngésző nyelvéhez, illetve a vizuális megjenése is függ a böngészőtől és op rendszertől)

Mondjuk szerintem eleve kevés ember akarná a nyilakkal egyesével növelni az irányítószámot, a "-" beírásást a Chrome beépített validációja pedig eddig is megfogta (mondjuk ez nem konzistens minden böngészőben). Ahogy azt @law909 is emltette, ennél bonyolultabb autocompletes, validációt építeni bonyolult lenne.

@pisipite - Jó lesz így? Lezárhatjuk ezt? Ha mindenképp kell ennél komolyabb, bolodbiztosabb validáció vagy az autocompletes megoldás, akkor javaslom arra nyissunk egy új issue-t pontosabb specifikációval.

![image](https://user-images.githubusercontent.com/6146591/188857234-65cb9fbb-5909-41f7-a53a-49910549e44e.png)

**Comment by pisipite** [comment]
aha, tök jó így!
