### ISSUE TITLE
kereső mezők sorrendje

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#58]
most így vannak elrendezve: ![kép](https://user-images.githubusercontent.com/25430950/188263135-c61a2c5e-691c-4ced-acc3-329f6639cb40.png)
jogcím-alap-forrás lenne jó egy sorban (bár ezt még módosíthatja az #57 -es issue), cégcsoport és támogatott entitás egy újban.

**Comment by Cooty** [comment]
@pisipite - Mobilon három mező nem fér ki egymás mellé, szóval most ez úgy néz ki, hogy a hármas tagolású sorból az utolsó mobil nézetben (992px alatt) betörik egy külön sorba.

**Comment by Cooty** [comment]
@pisipite 

Most így néz ki desktopban:


![Image](https://user-images.githubusercontent.com/6146591/188474255-1bb1d49f-7d9b-4c83-bc5b-8e06504adaa5.png)

és így néz ki mobilon

![Image](https://user-images.githubusercontent.com/6146591/188474421-020ec419-0758-4d16-8c51-797da6869ceb.png)

Jó lesz így?

**Comment by law909** [comment]
Mobilon külön sorba tenném a jogcímet, abban vannak hosszú szövegek, alá pedig az alapot és a forrást egy sorba.

**Comment by pisipite** [comment]
> @Cooty Mobilon külön sorba tenném a jogcímet, abban vannak hosszú szövegek, alá pedig az alapot és a forrást egy sorba.

aha! szerintem is így a legjobb.

**Comment by Cooty** [comment]
@pisipite - így?
![image](https://user-images.githubusercontent.com/6146591/188854855-7b9b85ee-e422-4217-ace0-769650330a11.png)

**Comment by pisipite** [comment]
szuper!
