### ISSUE TITLE
eredmények táblázat

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#66]

**Comment by pisipite** [comment]
![kép](https://user-images.githubusercontent.com/25430950/189208192-d349603f-b29e-4022-88e9-796bf613aa79.png)

- [ ] Gender > Nyertes jellege
- [ ] Csoport >Cégcsoport
- [ ] Csoport: csak a kapcsolódó cégcsoport neve jelenjen meg (_Támogatott entitás: xxx_ és _Cégcsoport:_ nem kell)
- [ ] Összeg > Összeg (Ft)
- [ ] Összeg: hármas tagolás

sorrenden annyit változtatnék, hogy a Név és Nyertes jellege (Gender) oszlopokat felcserélném.

**Comment by law909** [comment]
Csoport oszlop tartalmát másik issueban változtattuk, azt az állapotot hagyom meg.
