### ISSUE TITLE
Irányítószám, település szűrő működése

### ISSUE THREAD

**Issue by law909** [Code-for-Hungary/agrartamfront#76]
A következők valamelyikét kell csinálnunk:
- marad így szabadon beírós mindkettő. Irszámot csak 4 hosszút fogadunk el. Település név úgy fog működni, mint a név szűrő. @pisipite ha mindkettő meg van adva, melyik alapján keressünk/melyiket töröljem ki?
- összevonjuk egy mezőbe, ahol az adatbázisban lévő település+irszámok közül lehet választani, pl. mint jogcímek közül

@pisipite melyik legyen?

**Comment by pisipite** [comment]
legyen az egyes opció, félek, hogy lennének rendszeren kívüliségek, hibák a kettes esetében (pl. új település létrejötte (pl. Balatonakarattya)).
település legyen az elsőbbrendű. tök jó lenne, ha itt is lehetne többet kiválasztani.

**Comment by law909** [comment]
Az egyes megoldásban mindkét mező _szabadon beírós_, nem lehet sem egyet sem többet kiválasztani:)

**Comment by law909** [comment]
Az egyes megoldásnál a rendszeren kívüliségek, a hibák könnyebben kimaradhatnak a keresésekből, mert nem mutatjuk meg a lehetőségeket, hanem a felhasználó ír be feltételeket az általa ismert/sejtett lehetőségek alapján.

**Comment by law909** [comment]
@pisipite a fenti infókat is vedd figyelembe a döntéskor

**Comment by law909** [comment]
Telefonos megbeszélésünk alapján az irányítószám szűrőt elhagyjuk, a település pedig multiselect lesz, mint a jogcím.

**Comment by pisipite** [comment]
tök jó lett!
egy dolog: most irányítószámonként lehet kiválasztani településeket, viszont településenként nem lehet irányítószámokat. az olyan helyeknél, ahol egy településhez több szám tartozik kicsit macera az összeset kiválasztani. megoldási javaslat, hogy legyenek olyan sorok (pl. _Budapest (minden irányítószám)_), ami tartalmazza a település egészét.
