### ISSUE TITLE
Találati lista

### ISSUE THREAD

**Issue by law909** [Code-for-Hungary/agrartamfront#8]
@pisipite Milyen formában milyen adatok legyenek? Gondoljuk bele azt is, hogy már 3000 sor is túl sok képernyőn megjelenítésre és átlátni sem lehet.

**Comment by pisipite** [comment]
valami olyasmi találati oldal lapozó működne, mint a [redflagsen](https://www.redflags.eu/notices/10/1/by-date)? ott is sok-sok oldalnyi találatot tölt be, ha nincs szűrés: 
![kép](https://user-images.githubusercontent.com/25430950/185740219-b5ae4208-aeb9-401f-b248-c529b4b99746.png)
tartalomra (oszlopok és sorok) valami olyasmi formátum lenne a legjobb, mint maga az excel (valamivel kevesebb oszlopot megmutatva) minél több interaktivitással (szűrés, nő-férfi-cég piktogrammal, stb.). ezt próbáljam meg specifikálni valahogy?
