### ISSUE TITLE
 sor / oldal 

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamfront#80]
most ezek vannak: 15/30/45/60
legyen inkább: 15/50/100

**Comment by Cooty** [comment]
@pisipite - Megcsináltam, localban jónak tűnik, de nem számoltam meg a sorokat, hogy tényleg 50-e az 50. Kint van itt: https://agrartamfront.code4.hu/ nézd meg.

**Comment by pisipite** [comment]
szuper! 50 az 50, sőt 100 a 100!
